Allow parsing fractional `libtest` output
BurntSushi/cargo-benchcmp pull request #49
Opened 2024-05-12 14:37 UTC by Swatinem

This will now parse, but silently truncate the new fractional `libtest` output.

Fixes #48

2024-05-12 18:21 UTC, BurntSushi requested changes

2024-05-12 18:21 UTC, BurntSushi commented on src/benchmark.rs
> +        \s+...\sbench:\s+(?P<ns>[0-9,\.]+)\s+ns/iter  # ... bench: 1234 ns/iter
The escape for `.` is superfluous here, since `.` isn't a meta character inside a character class. Please remove it.

2024-08-29 16:41 UTC, cuviper commented
Thanks for this! I hadn't used the tool in a while, but just now I was confused that I wasn't getting any output. It's working for me again with this PR.

2024-08-29 16:43 UTC, BurntSushi approved these changes
LGTM

2024-08-29 16:44 UTC, merged

2024-08-29 16:45 UTC, BurntSushi commented
This PR is on crates.io in `cargo-benchcmp 0.4.5`.